### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#1]
Hey guys, i tried to run your SDK on Android operating system and got this error - 
```
D8: Program type already present: com.reactlibrary.BuildConfig



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:multiDexListDebug'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Error while merging dex archives: 

     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

     Program type already present: com.reactlibrary.BuildConfig



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 12s



error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

Note: Some input files use or override a deprecated API.
```

I tried to run project and also i got this error if try to create release build.

**Comment by hasismaeel5** [comment]
Hi. Are you using npm to get the SDK?

**Comment by EddyDunda** [comment]
@hasismaeel5, yes i installed package from npm, iOS version is running correct.

**Comment by hasismaeel5** [comment]
is the compileSDK version >= 17? Please look at https://github.com/voiceittech/VoiceIt2-React-Native-Demo for a running example of a react app that incorporates the SDK

**Comment by EddyDunda** [comment]
@hasismaeel5, yes i have correct compileSDK version:
```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
        androidXCore = "1.0.2"
    }
```

I tried your demo project and i have successfully run project. But i can't run your library in my project. Actually my react-native version is 0.63.2, and also i guess the problem with multidex, i have enabled multidex in my project, because i need it for my firebase libraries. P.S. - https://rnfirebase.io/enabling-multidex

**Comment by EddyDunda** [comment]
@hasismaeel5, i fixed it locally. Problem with default lib package name. You use default package name - "com.reactlibrary". And looks like some other library used the same name. I found the same issue in other library - https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/10

I just changed all names "com.reactlibrary" to "com.reactlibraryvoiceit" and it successfully builded.

**Comment by hasismaeel5** [comment]
Thanks for the feedback @EddyDunda  we'll implement that change. Let us know if there are further issues

**Comment by EddyDunda** [comment]
I still have this problem in 1.0.2.

**Comment by hasismaeel5** [comment]
Please pull 1.0.4 and try

**Comment by akshay247-voiceit** [comment]
You need to enable multidex support for your client applications native android code. IMHO, this has nothing to do with the library itself as the error log does not reference Voiceit RN library. 

You need to follow:
https://developer.android.com/studio/build/multidex
to get rid of this problem.

**Comment by EddyDunda** [comment]
@akshay247-voiceit, i have have enabled multidex support before install your package. Please read this comment - https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/1#issuecomment-758609245

**com.reactlibrary package name is the default name when initing a new RN plugin. It should be changed to prevent clashes with other packages that have not yet been renamed.**

**Comment by noeljgrover** [comment]
We will close this issue once we push new version 1.0.5

**Comment by hasismaeel5** [comment]
Hey @EddyDunda There was a confusion with this ticket- we thought you were having a build error beyond just changing the name from com.reactLibrary to something else. Anyhow, we just made a push to the SDK (It also included changes to make the Liveness tutorial optional). Please use 1.0.6
