### ISSUE TITLE
Question - Add Webhook

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#11]
H!i! In authentication section - https://api.voiceit.io/#authentication. I found ability to add Webhook Notification. How i can implement it with your react-native sdk to notify my server. You know it's looks like not security to ping server programatically form the client side.

**Comment by EddyDunda** [comment]
@hasismaeel5

**Comment by hasismaeel5** [comment]
Hi @EddyDunda Yes we are looking into this, we'll make a push of this feature by Monday hopefully

**Comment by hasismaeel5** [comment]
@EddyDunda thanks for the patience, we made a push. Please access the method myVoiceit.setNotificationURL("https://.....");
