### ISSUE TITLE
iOS Swipe down enrollment view

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#12]
Hey @hasismaeel5. If i swipe down enrollment view on iOS (close this view) i won't get any message about cancel event in callback.

```
Voiceit.encapsulatedFaceEnrollment(voiceItUserId, res => {
   console.log(res, 'Vace Enrollment');
}
  ```
Video: 

https://user-images.githubusercontent.com/69241200/112175741-272bc280-8c00-11eb-9220-c008265ef62a.mp4

**Comment by hasismaeel5** [comment]
Hi @EddyDunda The cancel callback is called if you cancel after starting the process. Unfortunately the SDK doesn't have the ability to send a callback for cancellation before starting the process, but if you head over to the "local installation" section of the read me file, you can see how to implement this SDK (and the Android + IOS sdks) locally so you can add any feature you like, such as the feature you desire above

**Comment by EddyDunda** [comment]
@hasismaeel5 i think it's incorrect. In case if i press on Cancel button on left side (yellow topbar) i will get cancel message in callback. I think you should just add this logic for swipe, too.

**Comment by noeljgrover** [comment]
The swipe event is tied to the parent application not the framework of the SDK. So, you would have to handle from application point. As the swipe event is a application event not interactive event on the storyboard of the framework.

**Comment by EddyDunda** [comment]
@noelgrover , check the video above. Unfortunately i don’t have access to this view and i think this is not a problem to add logic for swipe event from your sdk side and return this event in callback.

**Comment by noeljgrover** [comment]
@EddyDunda Thanks for the feedback. We are looking into adding other events and this swipe up event will be handled by the cancel workflow. We'll keep this open until the JIRA ticket is closed on our end.

**Comment by noeljgrover** [comment]
After further study it was concluded that a user would click on Cancel to exit the VoiceIt SDK User Flow. We are closing this ticket.
