### ISSUE TITLE
initVoiceIt with token crash

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#13]
@hasismaeel5 , @noelgrover
Hey, if i implement Voiceit initialization with token i will get a crash when tap on "Continue" button in face verification modal.
I use token generated with your api docs: https://api.voiceit.io/#user-token-generation

```
Voiceit.initVoiceIt(voiceItToken, '', () => {
      Voiceit.encapsulatedFaceVerification(
        biometricId,
        'no-STT',
        true,
        false,
        //false,
        result => {
          console.log(result, 'Result verify');
        },
      );
    });
```

P.S Method "encapsulatedFaceEnrollment" works correct with token initialization, also it's working correct with token and api key props.

**Comment by hasismaeel5** [comment]
Hi Eddy, we'll be implementing this feature soon

**Comment by hasismaeel5** [comment]
Hi Eddy, this should now work with our latest SDK. The user token must be generated first (https://api.voiceit.io/#user-token-generation) and then use the token in place of API_KEY and leave the API_TOKEN as blank when initializing
