### ISSUE TITLE
iOS Invalid userId

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#2]
When i tried to make face verification i got an app crash and caught error in Xcode - 
```
Exception NSException * "Invalid userId passed" 0x0000000280f14cc0. 
```

I got this error when called encapsulatedFaceVerification method. (I worked with the same userId for enrolment and verification)

**Comment by hasismaeel5** [comment]
Are you sure the order of parameters is correct? It must be encapsulatedFaceVerification:(
               userId
                 contentLanguage
                    doLivenessDetection
                         doAudioPrompts
                        callback....)
                        
Please look at https://github.com/voiceittech/VoiceIt2-React-Native-Demo for a running example of incorporating the SDK

**Comment by EddyDunda** [comment]
@hasismaeel5. I don't know how i fixed it, but looks like the problem was gone and i can't catch this error anymore. But i got another problem, i opened another issue: https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/5

**Comment by hasismaeel5** [comment]
Great job Eddy. We're looking at the other issues
