### ISSUE TITLE
Android Xiaomi view

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#4]
![2021-01-12 14 34 58](https://user-images.githubusercontent.com/69241200/104315287-67294780-54e3-11eb-8627-418ce2189039.jpg)

You can see bottom space with camera.

**Comment by hasismaeel5** [comment]
Thanks for this, we'll make a pr soon to fix this

**Comment by noeljgrover** [comment]
This is a device reporting bug on screen size. The code is correct. We suggest you can create a special case for this type of device and add the number of pixels to extent the white overlay.
