### ISSUE TITLE
iOS View issues

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#6]
View issues iPhone 7
- Missing fonts (Please look into the camera):
![2021-01-26 16 05 53](https://user-images.githubusercontent.com/69241200/105855110-623eba80-5ff0-11eb-84c7-73613858da83.jpg)

- Missing offset above "Is Ready" text:
![2021-01-26 16 08 10](https://user-images.githubusercontent.com/69241200/105855411-b8abf900-5ff0-11eb-8339-23a949f43276.jpg)

**Comment by noeljgrover** [comment]
Please provide Mobile Device Specs. So this can be scaled. Thank youl

**Comment by EddyDunda** [comment]
@noelgrover, this is iPhone 7.

**Comment by noeljgrover** [comment]
Please do pull 2.2.5 the storyboard has been changed to compensate.
