### ISSUE TITLE
Android brightness permission

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#7]
![2021-02-04 21 01 55](https://user-images.githubusercontent.com/69241200/106943654-5fe60a00-672e-11eb-8709-9a45d1046825.jpg)

How i can disable grant permission request and in general skip brightness permission. This feature not working correct.

**Comment by hasismaeel5** [comment]
@EddyDunda we just added a ticket for this feature, please wait a day or so for us to make a push

**Comment by hasismaeel5** [comment]
@EddyDunda Just removed this in 1.0.6
