### ISSUE TITLE
Android liveness tutorial

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#8]
![2021-02-04 21 03 57](https://user-images.githubusercontent.com/69241200/106944109-e26ec980-672e-11eb-9805-fd0219d96744.jpg)
How i can disable initial usage tutorial, i don't want to show it.

**Comment by hasismaeel5** [comment]
@EddyDunda we just added a ticket for this feature, please wait a day or so for us to make a push

**Comment by hasismaeel5** [comment]
@EddyDunda We just added this feature. For encapsulatedFaceVerification, and EncapsulatedVideoVerification, there is an extra argument before the callback argument- this argument is a boolean that will control the livenessTutorial. Refer to the ReadME for more info. Thanks
