### ISSUE TITLE
Enable liveness mode for testing

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#9]
I have successfully run liveness mode for iOS and Android platform. I just pay $10 in my account and now it's working. Also when i tried to run it in your demo project i got an email (i didn't receive it before):
```
Content Language Not Enabled
Hi Eduard,

Sorry, but the content language you used is not enabled in our free tier. Only no-STT is available in the free tier. Below is your JSON response:

{"message":"Only no-STT content language is enabled on the free tier","timeTaken":"0.058s","responseCode":"CLNE","status":400}

If you would like to enable this content language, please visit our Billing page to add funds.
```
Please provide this information in documentation and also maybe add default no-STT phrase in account.

**Comment by noeljgrover** [comment]
This email is sent if on Free Tier and you try to use something other than no-STT. We are in the process of updating Readme files, and new web site will be addressing the differences between free-tier and paid-tier.
